name: my_apps
description: A new Flutter project.

version: 1.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  async_redux: ^14.1.1
  freezed_annotation: ^2.0.1
  shared_preferences: ^2.0.13
  get_it: ^7.2.0
  injectable: ^1.5.3
  device_apps: ^2.2.0
  flutter_bloc: ^8.0.1
  firebase_core: ^1.18.0
  speech_to_text: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^2.0.2
  build_runner: ^2.1.11
  injectable_generator: ^1.5.3
  dart_code_metrics: ^4.15.2
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/apps_icon.jpg"
